#!/usr/bin/env python3
"""
convert_to_lerobot.py
=====================
Reads `trajectory_data.json` files generated by the headless PyFlex script, 
plays them back in Isaac Sim to capture camera frames, and saves the whole 
episode into a standard Hugging Face LeRobot dataset.
"""

import argparse
import os
import glob
import json
import numpy as np
import cv2
import sys
import shutil

try:
    from lerobot.common.datasets.lerobot_dataset import LeRobotDataset
except ImportError:
    print("ERROR: lerobot library not found. Please install it with:")
    print("pip install lerobot")
    sys.exit(1)

import config

parser = argparse.ArgumentParser()
parser.add_argument("--dataset-dir", required=True, help="Path to generated source dataset, e.g. /tmp/so100_fold_dataset/tshirt_sp_0")
parser.add_argument("--repo-id", default="ozan/so100_fold", help="LeRobot Dataset Repo ID (e.g., ozan/so100_fold)")
parser.add_argument("--local-dir", default=None, help="Local directory to store the lerobot dataset (default: ~/.cache/huggingface/lerobot/...)")
parser.add_argument("--fps", type=int, default=30)
parser.add_argument("--headless", action="store_true", default=True, help="Run Isaac Sim without viewport")
args, _ = parser.parse_known_args()

sim_app = config.get_simulation_app(headless=args.headless)

import omni.usd
from pxr import UsdGeom, UsdLux, Gf
import garment_loader
import cameras

World = config.get_world_cls()

try:
    from isaacsim.core.utils.stage import add_reference_to_stage
    from isaacsim.core.prims import SingleArticulation as Articulation
    from isaacsim.core.api.objects import FixedCuboid
except ImportError:
    from omni.isaac.core.utils.stage import add_reference_to_stage
    from omni.isaac.core.articulations import Articulation
    from omni.isaac.core.objects import FixedCuboid


def create_lerobot_dataset(repo_id, fps):
    # Definition of the standard robot features
    features = {
        "observation.images.wrist_left": {
            "dtype": "video",
            "shape": (config.WRIST_CAM_RESOLUTION[1], config.WRIST_CAM_RESOLUTION[0], 3),
            "names": ["height", "width", "channel"],
        },
        "observation.images.wrist_right": {
            "dtype": "video",
            "shape": (config.WRIST_CAM_RESOLUTION[1], config.WRIST_CAM_RESOLUTION[0], 3),
            "names": ["height", "width", "channel"],
        },
        "observation.state": {
            "dtype": "float32",
            "shape": (12,),
            "names": ["qpos"],
        },
        "action": {
            "dtype": "float32",
            "shape": (12,),
            "names": ["qpos"],
        },
    }
    
    root_dir = args.local_dir
    if root_dir is None:
        root_dir = os.path.expanduser(f"~/.cache/huggingface/lerobot/{repo_id}")
    
    if os.path.exists(root_dir):
        print(f"[lerobot] Warning: Dataset dir {root_dir} already exists. Appending to it.")
    
    dataset = LeRobotDataset.create(
        repo_id=repo_id,
        fps=fps,
        features=features,
        root=root_dir,
    )
    return dataset


def dict_to_qpos_array(qpos_dict, dof_names):
    return np.array([qpos_dict.get(n, 0.0) for n in dof_names], dtype=np.float32)


def main():
    world = World(stage_units_in_meters=1.0)
    stage = omni.usd.get_context().get_stage()

    physx = world.get_physics_context()
    physx.enable_gpu_dynamics(True)

    world.scene.add_default_ground_plane()
    dome = UsdLux.DomeLight.Define(stage, "/World/DomeLight")
    dome.CreateIntensityAttr(900.0)

    # Table
    tx, ty, tz = config.TABLE_SIZE
    table_center_z = config.TABLE_HEIGHT - tz / 2.0
    FixedCuboid(
        prim_path="/World/Table",
        name="table",
        position=np.array([0.0, 0.2, table_center_z]),
        scale=np.array([tx, ty, tz]),
        color=np.array([0.45, 0.30, 0.20]),
    )

    # Robot
    if config.USD_PATH.exists():
        add_reference_to_stage(str(config.USD_PATH), config.ROBOT_PRIM_PATH)
    else:
        print("[render] Error: Robot USD not found. Run import_urdf_to_usd.py first.")
        return

    robot_xform = UsdGeom.Xformable(stage.GetPrimAtPath(config.ROBOT_PRIM_PATH))
    robot_xform.ClearXformOpOrder()
    robot_xform.AddTranslateOp().Set(Gf.Vec3d(0.0, 0.0, config.TABLE_HEIGHT))

    robot = Articulation(prim_path=config.ROBOT_PRIM_PATH, name="so_100_dual")
    world.scene.add(robot)

    wrist_cams = cameras.add_wrist_cameras(
        stage, config, config.ROBOT_PRIM_PATH,
        make_sensors=True,
    )

    world.reset()
    if not robot.handles_initialized:
        robot.initialize()

    for cam in wrist_cams:
        if cam.sensor is not None:
            cam.sensor.initialize()

    dof_names = list(robot.dof_names)
    
    # Initialize LeRobot Dataset
    print(f"\n[lerobot] Initializing dataset: {args.repo_id}")
    dataset = create_lerobot_dataset(args.repo_id, args.fps)

    # Process Trajectories
    traj_dirs = sorted(glob.glob(os.path.join(args.dataset_dir, "traj_*")))
    print(f"[render] Found {len(traj_dirs)} trajectories in {args.dataset_dir}")

    for traj_dir in traj_dirs:
        print(f"\n[render] Processing {traj_dir} ...")
        meta_path = os.path.join(traj_dir, "meta.json")
        data_path = os.path.join(traj_dir, "trajectory_data.json")
        
        if not os.path.exists(meta_path) or not os.path.exists(data_path):
            print(f"[render] Missing meta.json or trajectory_data.json. Skipping.")
            continue

        with open(meta_path, 'r') as f:
            meta = json.load(f)
            
        with open(data_path, 'r') as f:
            trajectory_data = json.load(f)

        if len(trajectory_data) == 0:
            continue

        # Load cloth for visual reference in camera
        cloth_prim_path = "/World/Cloth/garmentMesh"
        surface_prim_path = "/World/Cloth/surfaceDeformable"
        if stage.GetPrimAtPath(cloth_prim_path).IsValid():
            stage.RemovePrim(cloth_prim_path)
        if stage.GetPrimAtPath(surface_prim_path).IsValid():
            stage.RemovePrim("/World/Cloth")

        cat = meta["garment"].rsplit("_", 1)[0]
        profile = config.get_garment_profile(cat)
        cx, cy, _ = config.CLOTH_CENTER
        cloth_center = (cx, cy, config.TABLE_HEIGHT + 0.005)
        
        garment_name = os.path.basename(args.dataset_dir) # e.g. tshirt_sp_0
        garment_loader.load_garment(
            stage=stage,
            scene_path="/physicsScene",
            root_path="/World/Cloth",
            garment_name=garment_name,
            garment_dir=str(config.GARMENT_DIR),
            scale=config.GARMENT_SCALE,
            center=cloth_center,
            particle_contact_offset=config.GARMENT_PARTICLE_CONTACT_OFFSET,
            profile=profile,
            mass=config.GARMENT_MASS,
            friction=config.GARMENT_FRICTION,
            backend="particle"
        )
        
        for _ in range(10):
            world.step(render=False)

        # Replay and Capture
        for idx, step_data in enumerate(trajectory_data):
            qpos_dict = step_data["qpos"]
            targets = dict_to_qpos_array(qpos_dict, dof_names)
            robot.set_joint_positions(targets)

            # Step physics and render
            world.step(render=True)

            rgba_l = wrist_cams[0].sensor.get_rgba()
            rgba_r = wrist_cams[1].sensor.get_rgba()
            
            # Note: LeRobot expects images in (H, W, C) RGB format
            img_l = rgba_l[:, :, :3] if rgba_l is not None else np.zeros((480, 640, 3), dtype=np.uint8)
            img_r = rgba_r[:, :, :3] if rgba_r is not None else np.zeros((480, 640, 3), dtype=np.uint8)
            
            # Action logic: predicting the next state (standard ACT format)
            if idx + 1 < len(trajectory_data):
                next_qpos = dict_to_qpos_array(trajectory_data[idx+1]["qpos"], dof_names)
            else:
                next_qpos = targets # last frame stays still

            frame_data = {
                "observation.state": targets,
                "observation.images.wrist_left": img_l,
                "observation.images.wrist_right": img_r,
                "action": next_qpos
            }
            
            dataset.add_frame(frame_data)
        
        dataset.save_episode(task="fold_garment")
        print(f"[lerobot] Episode saved successfully.")

    dataset.consolidate()
    print(f"\n[lerobot] Done! Dataset fully consolidated at {dataset.root}")

if __name__ == "__main__":
    main()
    sim_app.close()
